name: flutter_google_track_and_trace
description: An Iconica Flutter plugin for Track & Trace Package
version: 2.1.1
repository: https://github.com/Iconica-Development/flutter_google_track_and_trace

publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.6.1
  google_maps_flutter_web: ^0.5.7
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

false_secrets:
  - example/lib/main.dart
  - example/android/app/src/main/AndroidManifest.xml
